name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-python:
    uses: s3ntin3l8/.github/.github/workflows/ci-python.yml@main
    with:
      python-version: '3.12'
    secrets: inherit

  build-docker:
    needs: [test-python]
    uses: s3ntin3l8/.github/.github/workflows/docker-publish.yml@main
    with:
      image-name: 's3ntin3l8/${{ github.event.repository.name }}'
      push-edge: ${{ github.event_name == 'push' }}
    secrets: inherit
